# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

# We need Java 17 as per the Ghidra docs

name: Java CI with Gradle

on:
  push:
    branches: [ "mblinov-riscv-extensions" ]
  pull_request:
    branches: [ "mblinov-riscv-extensions" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup build environment
      run: gradle -I gradle/support/fetchDependencies.gradle init
    - name: Build with Gradle
      run: gradle --parallel buildGhidra
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-directory
        path: |
          build/dist/*
